using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace FirstDXDemo
{
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            courseDemoTableAdapter1.Fill(courseDemoDataSet1.CourseDemo);



            GridColumn hyperLinkColumn = (gridControl1.Views[0] as GridView).Columns["Link"];
            //...
            RepositoryItemHyperLinkEdit hyperLinkEdit = new RepositoryItemHyperLinkEdit();
            hyperLinkColumn.ColumnEdit = hyperLinkEdit; // this line associated hyperlink with column
            hyperLinkEdit.OpenLink += hyperLinkEdit_OpenLink;
            hyperLinkEdit.Click += hyperLinkEdit_Click;

            GridColumn statusColumn = (gridControl1.Views[0] as GridView).Columns["Status"];


            //GridColumn imageLinkColumn = (gridControl1.Views[0] as GridView).Columns["ImageLink"];

            //System.Net.WebClient webSource = new System.Net.WebClient();
            //byte[] data = webSource.DownloadData("http://www.expatax.nl/calculations/grosstonet/image002.png");
            //System.IO.MemoryStream pipe = new System.IO.MemoryStream(data);
            //Image jpgImage = Image.FromStream(pipe);



            //imageLinkColumn.Image = jpgImage;

            //...

        }

        void hyperLinkEdit_Click(object sender, EventArgs e)
        {
            //hyperLinkEdit_OpenLink(this, new DevExpress.XtraEditors.Controls.OpenLinkEventArgs(null));

        }

        void hyperLinkEdit_OpenLink(object sender, DevExpress.XtraEditors.Controls.OpenLinkEventArgs e)
        {
            System.Diagnostics.Trace.WriteLine("HyperLinkEdit clicked!");
        }

        private void officeNavigationBar1_SelectedItemChanged(object sender, DevExpress.XtraBars.Navigation.NavigationBarItemEventArgs e)
        {
            if (officeNavigationBar1.SelectedItem == navList)
            {
                gridControl1.MainView = gridView1;
            }
            else if (officeNavigationBar1.SelectedItem == navCards)
            {
                gridControl1.MainView = layoutView1;
            }
            else
            {
                ReportForm form = new ReportForm();
                form.Show();
            }
        }


    }
}
