using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace FirstDXDemo
{
    public partial class ReportForm : Form
    {
        public ReportForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            courseDemoTableAdapter5.Fill(courseDemoDataSet5.CourseDemo);
        }
    }
}
